apiVersion: v1
kind: Service
metadata:
  name: budget-backend-nodeport
spec:
  selector:
    app: budget-backend
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001
