apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-frontend
  template:
    metadata:
      labels:
        app: budget-frontend
    spec:
      containers:
        - name: budget-frontend
          image: kollijayanth2006/budget-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: budget-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: budget-frontend
